In [1]:
import pandas as pd

In [5]:
df = pd.read_csv("C:/Users/yashl/OneDrive/Desktop/Moneytrack AI/data/sample_transactions.csv")

In [6]:
df.head()

         Date Description  Amount     Type
0  2026-08-01      Salary   50000   Income
1  2026-08-02        Rent   12000  Expense
2  2026-08-03      Swiggy     850  Expense
3  2026-08-04        Uber     450  Expense
4  2026-08-05      Amazon    2200  Expense

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         24 non-null     str
 1   Description  24 non-null     str
 2   Amount       24 non-null     int64
 3   Type         24 non-null     str
dtypes: int64(1), str(3)
memory usage: 1.4 KB

In [9]:
df.describe()

             Amount
count     24.000000
mean    8187.375000
std    16444.327207
min      119.000000
25%      687.500000
50%     1099.500000
75%     2975.000000
max    50000.000000

In [10]:
df.shape

(24, 4)

In [11]:
df["Date"]=pd.to_datetime(df["Date"])

In [12]:
#basic calcultion

In [14]:
total_income=df.loc[df["Type"] =="Income","Amount"].sum()
print(total_income)

150000

In [15]:
total_expense = df.loc[df["Type"] == "Expense","Amount"].sum()
print(total_expense)

46497

In [16]:
saving = total_income-total_expense
print(saving)

103503

In [ ]:
if total_income > 0:
    savving_rate=(saving/total_income)*100
else:
    saving_Rate=0
print(savving_rate)

69.002

In [18]:
# ITEMS CATEGORIZATION  
def categorize_expense(description):

    description = str(description).lower()

    if any(word in description for word in [
        "swiggy", "zomato", "restaurant", "food"
    ]):
        return "Food"

    elif any(word in description for word in [
        "uber", "ola", "rapido", "metro", "bus",
        "train", "petrol", "fuel"
    ]):
        return "Transport"

    elif any(word in description for word in [
        "amazon", "flipkart", "myntra", "shopping"
    ]):
        return "Shopping"

    elif any(word in description for word in [
        "netflix", "spotify", "movie", "prime"
    ]):
        return "Entertainment"

    elif any(word in description for word in [
        "rent", "electricity", "internet", "water"
    ]):
        return "Bills & Housing"

    elif any(word in description for word in [
        "pharmacy", "hospital", "medical", "medicine"
    ]):
        return "Healthcare"

    elif any(word in description for word in [
        "salary", "income", "bonus"
    ]):
        return "Income"

    else:
        return "Other"

In [19]:
df["Category"] = df["Description"].apply(
    categorize_expense
)

In [20]:
df[["Description", "Amount", "Type", "Category"]]

         Description  Amount     Type         Category
0             Salary   50000   Income           Income
1               Rent   12000  Expense  Bills & Housing
2             Swiggy     850  Expense             Food
3               Uber     450  Expense        Transport
4             Amazon    2200  Expense         Shopping
5   Electricity Bill    1800  Expense  Bills & Housing
6         Restaurant    1200  Expense             Food
7            Netflix     649  Expense    Entertainment
8           Pharmacy     750  Expense       Healthcare
9           Shopping    3500  Expense         Shopping
10     Internet Bill     999  Expense  Bills & Housing
11            Salary   50000   Income           Income
12            Zomato     700  Expense             Food
13               Ola     380  Expense        Transport
14            Amazon    1500  Expense         Shopping
15  Electricity Bill    1600  Expense  Bills & Housing
16        Restaurant     900  Expense             Food
17           Spotify     119  Expense    Entertainment
18          Medicine     650  Expense       Healthcare
19          Shopping    2800  Expense         Shopping
20            Salary   50000   Income           Income
21              Uber     500  Expense        Transport
22            Swiggy     950  Expense             Food
23              Rent   12000  Expense  Bills & Housing

In [21]:
expense_by_category = (
    df[df["Type"] == "Expense"]
    .groupby("Category")["Amount"]
    .sum()
    .sort_values(ascending=False)
)

expense_by_category

Category
Bills & Housing    28399
Shopping           10000
Food                4600
Healthcare          1400
Transport           1330
Entertainment        768
Name: Amount, dtype: int64

In [16]:
import plotly.express as px

In [17]:
category_df = expense_by_category.reset_index()

category_df

          Category  Amount
0  Bills & Housing   28399
1         Shopping   10000
2             Food    4600
3       Healthcare    1400
4        Transport    1330
5    Entertainment     768

In [9]:
import plotly.express as px
import pandas as pd

In [10]:
df = pd.read_csv("C:/Users/yashl/OneDrive/Desktop/Moneytrack AI/data/sample_transactions.csv")

In [24]:
fig = px.bar(
    category_df,
    x="Category",
    y="Amount",
    title="Expenses by Category",
    text="Amount"
)

fig

In [26]:
df["Date"] = pd.to_datetime(df["Date"])

In [28]:
df["Date"].dtype

dtype('<M8[us]')

In [29]:
df["Month"] = df["Date"].dt.to_period("M").astype(str)

In [30]:
monthly_income = (
    df[df["Type"] == "Income"]
    .groupby("Month")["Amount"]
    .sum()
)

monthly_income

Month
2026-08    150000
Name: Amount, dtype: int64

In [31]:
monthly_expenses = (
    df[df["Type"] == "Expense"]
    .groupby("Month")["Amount"]
    .sum()
)

monthly_expenses

Month
2026-08    46497
Name: Amount, dtype: int64

In [32]:
monthly_savings = (
    monthly_income
    .subtract(monthly_expenses, fill_value=0)
)

monthly_savings

Month
2026-08    103503
Name: Amount, dtype: int64

In [33]:
monthly_summary = pd.DataFrame({
    "Income": monthly_income,
    "Expenses": monthly_expenses,
    "Savings": monthly_savings
}).fillna(0)

monthly_summary

         Income  Expenses  Savings
Month
2026-08  150000     46497   103503

In [34]:
fig = px.line(
    monthly_summary.reset_index(),
    x="Month",
    y="Expenses",
    markers=True,
    title="Monthly Expense Trend"
)

fig

In [15]:
import pandas as pd
import numpy as np

dates = pd.date_range(
    start="2025-01-01",
    end="2025-12-31",
    freq="D"
)

data = []

for date in dates: 

    income = np.random.randint(40000, 60000)

    expense = np.random.randint(15000, 35000)

    savings = income - expense

    data.append([
        date,
        income,
        expense,
        savings
    ])

ml_df = pd.DataFrame(
    data,
    columns=[
        "Date",
        "Income",
        "Expense",
        "Savings"
    ]
)

ml_df.head()

        Date  Income  Expense  Savings
0 2025-01-01   51661    15979    35682
1 2025-01-02   50191    25621    24570
2 2025-01-03   45008    19451    25557
3 2025-01-04   44137    29457    14680
4 2025-01-05   55757    25852    29905

In [25]:
ml_df.shape

(365, 4)

In [16]:
ml_df.to_csv(
    "C:/Users/yashl/OneDrive/Desktop/Moneytrack AI/data/financial_history.csv",
    index=False
)

print("Dataset Saved")

Dataset Saved

In [ ]:
# Load our ML dataset
"""ml_df = pd.read_csv("C:/Users/yashl/OneDrive/Desktop/Moneytrack AI/data/financial_history.csv")

# Convert Date to datetime
ml_df["Date"] = pd.to_datetime(ml_df["Date"])

# Create Month column
ml_df["Month"] = ml_df["Date"].dt.to_period("M")

# Calculate monthly expenses 
monthly_ml = (
    ml_df.groupby("Month")["Expense"]
    .sum()
    .reset_index()
)

monthly_ml"""

      Month  Expense
0   2025-01   786801
1   2025-02   733577
2   2025-03   686166
3   2025-04   698658
4   2025-05   795790
5   2025-06   802741
6   2025-07   777389
7   2025-08   744624
8   2025-09   730263
9   2025-10   742231
10  2025-11   683258
11  2025-12   807663

In [ ]:
# Convert Month to text for Plotly
"""monthly_ml["Month"] = monthly_ml["Month"].astype(str)

fig = px.line(
    monthly_ml,
    x="Month",
    y=["Expense", "Predicted_Expense"],
    markers=True,
    title="Actual vs Predicted Monthly Expenses"
)

fig"""

In [ ]:
model_results = pd.DataFrame({
    "Metric": ["MAE", "R² Score"],
    "Value": [mae, r2]
})

model_results

     Metric         Value
0       MAE  37612.956294
1  R² Score      0.001730

1 ML MODEL - MONTHLY EXPENSE FORCASTING

In [ ]:
import numpy as np
import pandas as pd

np.random.seed(42)

months = pd.date_range(
    start="2025-01-01",
    periods=12,
    freq="MS"
)

base_expense = 20000

expenses = []

for i in range(12):
    trend = i * 800
    variation = np.random.randint(-1500, 1500)

    expense = base_expense + trend + variation

    expenses.append(expense)

monthly_ml = pd.DataFrame({
    "Month": months,
    "Expense": expenses
})

monthly_ml

        Month  Expense
0  2025-01-01    19360
1  2025-02-01    20594
2  2025-03-01    21230
3  2025-04-01    21995
4  2025-05-01    23338
5  2025-06-01    24669
6  2025-07-01    23766
7  2025-08-01    25338
8  2025-09-01    25230
9  2025-10-01    27182
10 2025-11-01    28635
11 2025-12-01    30219

In [54]:
monthly_ml["Month_Number"] = range(
    1,
    len(monthly_ml) + 1
)

monthly_ml

        Month  Expense  Month_Number
0  2025-01-01    19360             1
1  2025-02-01    20594             2
2  2025-03-01    21230             3
3  2025-04-01    21995             4
4  2025-05-01    23338             5
5  2025-06-01    24669             6
6  2025-07-01    23766             7
7  2025-08-01    25338             8
8  2025-09-01    25230             9
9  2025-10-01    27182            10
10 2025-11-01    28635            11
11 2025-12-01    30219            12

In [ ]:
from sklearn.linear_model import LinearRegression

X = monthly_ml[["Month_Number"]] 
y = monthly_ml["Expense"]

model = LinearRegression()

model.fit(X, y)

LinearRegression()

In [ ]:
from sklearn.metrics import mean_absolute_error, r2_score

y_pred = model.predict(X)

mae = mean_absolute_error(y, y_pred) 
r2 = r2_score(y, y_pred) 

print(f"MAE: ₹{mae:,.2f}") 
print(f"R² Score: {r2:.2f}")

MAE: ₹484.50
R² Score: 0.96

In [ ]:
next_month = pd.DataFrame({
    "Month_Number": [13]
})

predicted_expense = model.predict(next_month)[0] 

print(
    f"Predicted Next Month Expense: ₹{predicted_expense:,.2f}"
)

Predicted Next Month Expense: ₹30,086.20

In [58]:
monthly_ml["Predicted_Expense"] = model.predict(X)

fig = px.line(
    monthly_ml,
    x="Month",
    y=["Expense", "Predicted_Expense"],
    markers=True,
    title="Actual vs Predicted Monthly Expenses"
)

fig

In [ ]:
# 2 ML MODEL - Savings Health Classification.

In [13]:
print(ml_df)

NameError: name 'ml_df' is not defined

In [20]:
import pandas as pd

In [27]:
ml_df.head()

        Date  Income  Expense  Savings
0 2025-01-01   40055    28013    12042
1 2025-01-02   48717    23150    25567
2 2025-01-03   42125    26479    15646
3 2025-01-04   55745    31748    23997
4 2025-01-05   46809    19621    27188

In [ ]:
import numpy as np
import pandas as pd

np.random.seed(42)

n = 200

income = np.random.randint(20000, 100001, n)
expense = np.random.randint(10000, 90001, n)

expense = np.minimum(expense, income - 1000)

savings = income - expense

savings_rate = (savings / income) * 100

savings_health_df = pd.DataFrame({
    "Income": income,
    "Expense": expense,
    "Savings": savings,
    "Savings_Rate": savings_rate
})

savings_health_df.head()

   Income  Expense  Savings  Savings_Rate
0   35795    21111    14684     41.022489
1   20860    19860     1000      4.793864
2   96820    11802    85018     87.810370
3   74886    18155    56731     75.756483
4   26265    25265     1000      3.807348

In [29]:
def savings_health(rate):

    if rate < 10:
        return "Poor"

    elif rate < 20:
        return "Average"

    elif rate < 30:
        return "Good"

    else:
        return "Excellent"

In [30]:
savings_health_df["Health"] = (
    savings_health_df["Savings_Rate"]
    .apply(savings_health)
)

savings_health_df.head()

   Income  Expense  Savings  Savings_Rate     Health
0   35795    21111    14684     41.022489  Excellent
1   20860    19860     1000      4.793864       Poor
2   96820    11802    85018     87.810370  Excellent
3   74886    18155    56731     75.756483  Excellent
4   26265    25265     1000      3.807348       Poor

In [31]:
savings_health_df["Health"].value_counts()

Health
Excellent    86
Poor         85
Good         17
Average      12
Name: count, dtype: int64

In [32]:
X = savings_health_df[
    ["Income", "Expense", "Savings", "Savings_Rate"]
]

y = savings_health_df["Health"]

In [33]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

In [34]:
from sklearn.tree import DecisionTreeClassifier

model2 = DecisionTreeClassifier(
    max_depth=3,
    random_state=42
)

In [35]:
model2.fit(
    X_train,
    y_train
)

DecisionTreeClassifier(max_depth=3, random_state=42)

In [36]:
y_pred2 = model2.predict(X_test)

y_pred2[:10]

array(['Good', 'Poor', 'Poor', 'Excellent', 'Average', 'Excellent',
       'Excellent', 'Poor', 'Excellent', 'Poor'], dtype=object)

In [ ]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(
    y_test,
    y_pred2 
)

print(f"Model 2 Accuracy: {accuracy:.2%}")

Model 2 Accuracy: 100.00%

In [38]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_test,
        y_pred2,
        zero_division=0
    )
)

              precision    recall  f1-score   support

     Average       1.00      1.00      1.00         3
   Excellent       1.00      1.00      1.00        22
        Good       1.00      1.00      1.00         4
        Poor       1.00      1.00      1.00        21

    accuracy                           1.00        50
   macro avg       1.00      1.00      1.00        50
weighted avg       1.00      1.00      1.00        50

In [39]:
new_user = pd.DataFrame({
    "Income": [50000],
    "Expense": [35000],
    "Savings": [15000],
    "Savings_Rate": [30]
})

prediction = model2.predict(new_user)

print("Predicted Savings Health:", prediction[0])

Predicted Savings Health: Excellent

In [1]:
# 1 AI FEATURE

In [2]:
def financial_advisor(
    income,
    expenses,
    savings,
    savings_rate,
    highest_category
):

    advice = []

    # Check savings
    if savings_rate < 10:
        advice.append(
            "Your savings rate is low. "
            "Focus on reducing unnecessary expenses."
        )

    elif savings_rate < 20:
        advice.append(
            "Your savings rate is moderate. "
            "Try to increase your monthly savings gradually."
        )

    elif savings_rate < 30:
        advice.append(
            "Your savings rate is healthy. "
            "Continue maintaining your saving habit."
        )

    else:
        advice.append(
            "Your savings rate is strong. "
            "Continue maintaining disciplined spending."
        )

    # Check highest spending category
    if highest_category:
        advice.append(
            f"Your highest spending category is "
            f"{highest_category}. Review this category "
            f"for unnecessary expenses."
        )

    # Check expense ratio
    expense_ratio = (expenses / income) * 100

    if expense_ratio > 80:
        advice.append(
            "Your expenses are using a large portion "
            "of your income. Consider setting a spending limit."
        )

    elif expense_ratio < 50:
        advice.append(
            "Your expenses are relatively controlled "
            "compared with your income."
        )

    return advice

In [3]:
advice = financial_advisor(
    income=50000,
    expenses=42000,
    savings=8000,
    savings_rate=16,
    highest_category="Shopping"
)

advice

['Your savings rate is moderate. Try to increase your monthly savings gradually.',
 'Your highest spending category is Shopping. Review this category for unnecessary expenses.',
 'Your expenses are using a large portion of your income. Consider setting a spending limit.']

In [4]:
for item in advice:
    print("💡", item)

💡 Your savings rate is moderate. Try to increase your monthly savings gradually.
💡 Your highest spending category is Shopping. Review this category for unnecessary expenses.
💡 Your expenses are using a large portion of your income. Consider setting a spending limit.

In [11]:
total_income = df[df["Type"] == "Income"]["Amount"].sum()

total_expenses = df[df["Type"] == "Expense"]["Amount"].sum()

total_savings = total_income - total_expenses

savings_rate = (
    total_savings / total_income
) * 100

print(f"Total Income: ₹{total_income:,.2f}")
print(f"Total Expenses: ₹{total_expenses:,.2f}")
print(f"Total Savings: ₹{total_savings:,.2f}")
print(f"Savings Rate: {savings_rate:.2f}%")

Total Income: ₹150,000.00
Total Expenses: ₹46,497.00
Total Savings: ₹103,503.00
Savings Rate: 69.00%

In [22]:
expense_by_category = (
    df[df["Type"] == "Expense"]
    .groupby("Category")["Amount"]
    .sum()
    .sort_values(ascending=False)
)

highest_category = expense_by_category.index[0]

print("Highest Spending Category:", highest_category)

Highest Spending Category: Bills & Housing

In [23]:
advice = financial_advisor(
    income=total_income,
    expenses=total_expenses,
    savings=total_savings,
    savings_rate=savings_rate,
    highest_category=highest_category
)

for item in advice:
    print("💡", item)

💡 Your savings rate is strong. Continue maintaining disciplined spending.
💡 Your highest spending category is Bills & Housing. Review this category for unnecessary expenses.
💡 Your expenses are relatively controlled compared with your income.

In [24]:
# 2 AI RULE BASED MODEL

In [25]:
def goal_planner(
    goal_amount,
    current_savings,
    monthly_savings,
    months
):
    
    remaining_amount = goal_amount - current_savings
    
    if remaining_amount <= 0:
        return {
            "status": "Goal Already Achieved",
            "message": "You have already reached your savings goal."
        }
    
    required_monthly_saving = (
        remaining_amount / months
    )
    
    if monthly_savings >= required_monthly_saving:
        status = "Goal Achievable"
        
        message = (
            f"You need to save ₹{required_monthly_saving:,.2f} "
            f"per month. Your current monthly saving of "
            f"₹{monthly_savings:,.2f} is sufficient."
        )
        
    else:
        status = "Needs Improvement"
        
        message = (
            f"You need to save ₹{required_monthly_saving:,.2f} "
            f"per month. Your current monthly saving of "
            f"₹{monthly_savings:,.2f} is not sufficient."
        )
    
    return {
        "status": status,
        "required_monthly_saving": required_monthly_saving,
        "message": message
    }

In [26]:
goal_result = goal_planner(
    goal_amount=100000,
    current_savings=20000,
    monthly_savings=25000,
    months=4
)

goal_result

{'status': 'Goal Achievable',
 'required_monthly_saving': 20000.0,
 'message': 'You need to save ₹20,000.00 per month. Your current monthly saving of ₹25,000.00 is sufficient.'}

In [27]:
print("🎯 Goal Status:", goal_result["status"])

if "required_monthly_saving" in goal_result:
    print(
        f"💰 Required Monthly Saving: "
        f"₹{goal_result['required_monthly_saving']:,.2f}"
    )

print("💡", goal_result["message"])

🎯 Goal Status: Goal Achievable
💰 Required Monthly Saving: ₹20,000.00
💡 You need to save ₹20,000.00 per month. Your current monthly saving of ₹25,000.00 is sufficient.

In [28]:
goal_result = goal_planner(
    goal_amount=200000,
    current_savings=20000,
    monthly_savings=15000,
    months=4
)

print("🎯 Goal Status:", goal_result["status"])

if "required_monthly_saving" in goal_result:
    print(
        f"💰 Required Monthly Saving: "
        f"₹{goal_result['required_monthly_saving']:,.2f}"
    )

print("💡", goal_result["message"])

🎯 Goal Status: Needs Improvement
💰 Required Monthly Saving: ₹45,000.00
💡 You need to save ₹45,000.00 per month. Your current monthly saving of ₹15,000.00 is not sufficient.

In [29]:
# 🔮 AI Feature 3 — What-If Financial Simulator

In [30]:
def what_if_simulator(
    income,
    expenses,
    savings,
    change_type,
    change_percent
):

    if change_type == "expense_reduction":

        reduction = expenses * (change_percent / 100)

        new_expenses = expenses - reduction

        new_savings = income - new_expenses

        savings_change = new_savings - savings

        return {
            "Current Expenses": expenses,
            "New Expenses": new_expenses,
            "Extra Savings": savings_change
        }

    elif change_type == "income_increase":

        increase = income * (change_percent / 100)

        new_income = income + increase

        new_savings = new_income - expenses

        savings_change = new_savings - savings

        return {
            "Current Income": income,
            "New Income": new_income,
            "Extra Savings": savings_change
        }

In [31]:
result = what_if_simulator(
    income=50000,
    expenses=40000,
    savings=10000,
    change_type="expense_reduction",
    change_percent=20
)

result

{'Current Expenses': 40000, 'New Expenses': 32000.0, 'Extra Savings': 8000.0}

In [32]:
print("🔮 WHAT-IF SIMULATION")
print("----------------------")

for key, value in result.items():
    print(f"{key}: ₹{value:,.2f}")

🔮 WHAT-IF SIMULATION
----------------------
Current Expenses: ₹40,000.00
New Expenses: ₹32,000.00
Extra Savings: ₹8,000.00

In [33]:
result = what_if_simulator(
    income=50000,
    expenses=40000,
    savings=10000,
    change_type="income_increase",
    change_percent=10
)

result

{'Current Income': 50000, 'New Income': 55000.0, 'Extra Savings': 5000.0}

In [34]:
expense_by_category

Category
Bills & Housing    28399
Shopping           10000
Food                4600
Healthcare          1400
Transport           1330
Entertainment        768
Name: Amount, dtype: int64

In [35]:
category = "Shopping"
reduction_percent = 20

current_category_expense = expense_by_category[category]

reduction = (
    current_category_expense *
    reduction_percent / 100
)

new_category_expense = (
    current_category_expense - reduction
)

print("Category:", category)
print(
    f"Current Expense: ₹{current_category_expense:,.2f}"
)
print(
    f"Reduction: ₹{reduction:,.2f}"
)
print(
    f"New Expense: ₹{new_category_expense:,.2f}"
)

Category: Shopping
Current Expense: ₹10,000.00
Reduction: ₹2,000.00
New Expense: ₹8,000.00

In [36]:
total_income = df[df["Type"] == "Income"]["Amount"].sum()

total_expenses = df[df["Type"] == "Expense"]["Amount"].sum()

total_savings = total_income - total_expenses

print(f"Income: ₹{total_income:,.2f}")
print(f"Expenses: ₹{total_expenses:,.2f}")
print(f"Savings: ₹{total_savings:,.2f}")

Income: ₹150,000.00
Expenses: ₹46,497.00
Savings: ₹103,503.00

In [37]:
def category_what_if(
    expense_by_category,
    total_expenses,
    category,
    reduction_percent
):

    current_category_expense = expense_by_category[category]

    reduction = (
        current_category_expense *
        reduction_percent / 100
    )

    new_category_expense = (
        current_category_expense - reduction
    )

    new_total_expenses = (
        total_expenses - reduction
    )

    extra_savings = reduction

    return {
        "Category": category,
        "Current Category Expense": current_category_expense,
        "Reduction": reduction,
        "New Category Expense": new_category_expense,
        "New Total Expenses": new_total_expenses,
        "Extra Savings": extra_savings
    }

In [38]:
expense_by_category

Category
Bills & Housing    28399
Shopping           10000
Food                4600
Healthcare          1400
Transport           1330
Entertainment        768
Name: Amount, dtype: int64

In [39]:
result = category_what_if(
    expense_by_category=expense_by_category,
    total_expenses=total_expenses,
    category="Shopping",
    reduction_percent=20
)

result

{'Category': 'Shopping',
 'Current Category Expense': np.int64(10000),
 'Reduction': np.float64(2000.0),
 'New Category Expense': np.float64(8000.0),
 'New Total Expenses': np.float64(44497.0),
 'Extra Savings': np.float64(2000.0)}

In [40]:
print("🔮 WHAT-IF FINANCIAL SIMULATION")
print("--------------------------------")

print(
    f"Category: {result['Category']}"
)

print(
    f"Current Spending: "
    f"₹{result['Current Category Expense']:,.2f}"
)

print(
    f"Potential Reduction: "
    f"₹{result['Reduction']:,.2f}"
)

print(
    f"New Category Spending: "
    f"₹{result['New Category Expense']:,.2f}"
)

print(
    f"New Total Expenses: "
    f"₹{result['New Total Expenses']:,.2f}"
)

print(
    f"💰 Extra Savings: "
    f"₹{result['Extra Savings']:,.2f}"
)

🔮 WHAT-IF FINANCIAL SIMULATION
--------------------------------
Category: Shopping
Current Spending: ₹10,000.00
Potential Reduction: ₹2,000.00
New Category Spending: ₹8,000.00
New Total Expenses: ₹44,497.00
💰 Extra Savings: ₹2,000.00

In [41]:
new_total_savings = (
    total_savings +
    result["Extra Savings"]
)

print(
    f"Current Savings: ₹{total_savings:,.2f}"
)

print(
    f"New Savings: ₹{new_total_savings:,.2f}"
)

Current Savings: ₹103,503.00
New Savings: ₹105,503.00